[profile.default]
src = "src"
out = "out"
libs = ["lib"]


remappings = [
    '@chainlink/contracts-ccip/=lib/ccip/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@chainlink/contracts/=lib/chainlink/contracts/',
    '@chainlink/local/=lib/chainlink-local/',
]

solc = '0.8.24'
evm_version = 'paris'

[rpc_endpoints]
arbitrumSepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
